import type { WeeklyProjectedPlayer, ProjectedStatLine } from '@/lib/fantasy/lineup-types';
import type { NflverseTeamWeek } from '@/lib/fantasy/nflverse-team-stats';
import type { ProjectionOverrideRecord } from '@/lib/fantasy/projection-overrides';
import type { PlayerProjectionCandidate, TeamOpportunityPlan, UsageProfile } from '@/lib/fantasy/projection-opportunity-types';
import { buildUsageProfile, carryPrior, clamp, finite, participationFactor, passPrior, targetPrior } from '@/lib/fantasy/projection-usage';
import { projectTeamOpportunityPlan } from '@/lib/fantasy/projection-team-plan';

function score(statLine:ProjectedStatLine,scoring:Record<string,number>,position:string):number{let points=0;for(const[key,m]of Object.entries(scoring)){if(!Number.isFinite(m)||m===0)continue;if(key==='bonus_rec_te'&&position==='TE'){points+=(statLine.rec||0)*m;continue;}if(key==='bonus_rec_wr'&&position==='WR'){points+=(statLine.rec||0)*m;continue;}if(key==='bonus_rec_rb'&&position==='RB'){points+=(statLine.rec||0)*m;continue;}const v=statLine[key];if(Number.isFinite(v))points+=v*m;}return points;}
type Allocation={amount:number;share:number;profile:UsageProfile};
function allocatePool(args:{candidates:PlayerProjectionCandidate[];pool:number;eligible:(c:PlayerProjectionCandidate)=>boolean;rawWeight:(c:PlayerProjectionCandidate,p:UsageProfile)=>number;overrideShare:(o:ProjectionOverrideRecord|undefined)=>number|null}):Map<string,Allocation>{
 const eligible=args.candidates.filter(args.eligible);const profiles=new Map(eligible.map(c=>[c.id,buildUsageProfile(c)]as const));const fixed=new Map<string,number>();
 for(const c of eligible){const o=args.overrideShare(c.override);if(o!=null&&Number.isFinite(o))fixed.set(c.id,clamp(o,0,1));}
 const fixedTotal=[...fixed.values()].reduce((s,v)=>s+v,0);const scale=fixedTotal>0.98?0.98/fixedTotal:1;const remaining=Math.max(0,1-fixedTotal*scale);const variable=eligible.filter(c=>!fixed.has(c.id));const raw=new Map<string,number>();
 for(const c of variable){const p=profiles.get(c.id)!;const active=clamp(c.override?.activeProbability??c.base.activeProbability,0,1);const availability=active<0.2?active:0.85+(0.15*active);raw.set(c.id,Math.max(0.0001,args.rawWeight(c,p)*availability));}
 const total=[...raw.values()].reduce((s,v)=>s+v,0);const out=new Map<string,Allocation>();
 for(const c of eligible){const p=profiles.get(c.id)!;const share=fixed.has(c.id)?(fixed.get(c.id)||0)*scale:variable.length?(total>0?remaining*((raw.get(c.id)||0)/total):remaining/variable.length):0;out.set(c.id,{amount:args.pool*share,share,profile:p});}
 return out;
}
function rate(line:ProjectedStatLine,n:string,d:string,fallback:number):number{const den=finite(line[d]);return den>0?finite(line[n])/den:fallback;}
function soften(factor:number,weight=0.55):number{return 1+((factor-1)*weight);}
function refreshBonuses(line:ProjectedStatLine,position:string):void{if(position==='QB'){const y=finite(line.pass_yd);line.bonus_pass_yd_300=clamp((y-250)/100,0,1);line.bonus_pass_yd_400=clamp((y-350)/100,0,1);}if(['QB','RB','WR','TE'].includes(position)){const y=finite(line.rush_yd);line.bonus_rush_yd_100=clamp((y-75)/75,0,1);line.bonus_rush_yd_200=clamp((y-175)/75,0,1);}if(['RB','WR','TE'].includes(position)){const y=finite(line.rec_yd);line.bonus_rec_yd_100=clamp((y-75)/75,0,1);line.bonus_rec_yd_200=clamp((y-175)/75,0,1);}}
function roleLabel(c:PlayerProjectionCandidate,t:number,r:number,p:number):string{if(c.override?.roleLabel)return c.override.roleLabel;const pos=c.base.position;if(pos==='QB')return p>=.72?'Expected starting quarterback':p>=.18?'Potential quarterback rotation':'Backup quarterback';if(pos==='RB')return r>=.5||(r>=.38&&t>=.1)?'Lead back':r>=.22||t>=.1?'Committee / secondary back':'Change-of-pace / depth back';if(pos==='WR')return t>=.24?'Featured starting receiver':t>=.15?'Starting receiver':t>=.08?'Slot / rotational receiver':'Depth receiver';if(pos==='TE')return t>=.16?'Lead tight end':t>=.08?'Secondary tight end':'Blocking / depth tight end';return c.base.expectedRole;}
function mergeAssumption(...parts:Array<string|null|undefined>):string|null{const v=parts.map(p=>String(p||'').trim()).filter(Boolean);return v.length?Array.from(new Set(v)).join(' '):null;}
export function reconcileTeamOpportunityBudgets(args:{candidates:PlayerProjectionCandidate[];currentRowsByTeam:Map<string,NflverseTeamWeek[]>;previousRowsByTeam:Map<string,NflverseTeamWeek[]>;preseason:boolean;scoring:Record<string,number>;teamOverrides:Map<string,ProjectionOverrideRecord>}):{players:WeeklyProjectedPlayer[];plans:Record<string,TeamOpportunityPlan>}{
 const byTeam=new Map<string,PlayerProjectionCandidate[]>();const passthrough:WeeklyProjectedPlayer[]=[];for(const c of args.candidates){const team=c.base.nflTeam;if(!team||c.base.isBye){passthrough.push(c.base);continue;}const list=byTeam.get(team)||[];list.push(c);byTeam.set(team,list);}const players=[...passthrough];const plans:Record<string,TeamOpportunityPlan>={};
 for(const[team,candidates]of byTeam){const plan=projectTeamOpportunityPlan({team,currentRows:args.currentRowsByTeam.get(team)||[],previousRows:args.previousRowsByTeam.get(team)||[],candidates,preseason:args.preseason,teamOverride:args.teamOverrides.get(team)});plans[team]=plan;
  const passes=allocatePool({candidates,pool:plan.passAttempts,eligible:c=>c.base.position==='QB',rawWeight:passPrior,overrideShare:o=>o?.passAttemptShare??null});
  const targets=allocatePool({candidates,pool:plan.targetPool,eligible:c=>['RB','WR','TE'].includes(c.base.position),rawWeight:targetPrior,overrideShare:o=>o?.targetShare??null});
  const carries=allocatePool({candidates,pool:plan.rushAttempts,eligible:c=>['QB','RB','WR'].includes(c.base.position),rawWeight:carryPrior,overrideShare:o=>o?.carryShare??null});
  for(const c of candidates){const position=c.base.position;if(!['QB','RB','WR','TE'].includes(position)){players.push({...c.base,teamPassAttempts:Number(plan.passAttempts.toFixed(1)),teamRushAttempts:Number(plan.rushAttempts.toFixed(1)),allocationSource:plan.source,workloadUncertainty:plan.uncertaintyMultiplier,overrideApplied:Boolean(c.override)});continue;}
   const original=c.base.statLine||{};const line:ProjectedStatLine={...original};const pass=passes.get(c.id),target=targets.get(c.id),carry=carries.get(c.id);const targetShare=target?.share||0,carryShare=carry?.share||0,passShare=pass?.share||0;const profile=pass?.profile||target?.profile||carry?.profile||buildUsageProfile(c);const active=clamp(c.override?.activeProbability??c.base.activeProbability,0,1);const start=clamp(c.override?.startProbability??c.base.startProbability,0,1);
   if(position==='QB'){const a=pass?.amount||0;const cr=clamp(rate(original,'pass_cmp','pass_att',.635),.48,.76);const ypa=clamp(rate(original,'pass_yd','pass_att',6.8)*soften(plan.passingEfficiencyFactor),5.1,9.3);const tdr=clamp(rate(original,'pass_td','pass_att',.043)*soften(plan.passingTouchdownFactor),.018,.075);const ir=clamp(rate(original,'pass_int','pass_att',.023)/Math.max(.97,soften(plan.passingEfficiencyFactor)),.008,.05);line.pass_att=a;line.pass_cmp=a*cr;line.pass_inc=Math.max(0,a-line.pass_cmp);line.pass_yd=a*ypa;line.pass_td=a*tdr;line.pass_int=a*ir;line.pass_fd=line.pass_cmp*.49;line.pass_2pt=.04*active*start;}
   if(['QB','RB','WR'].includes(position)){const a=carry?.amount||0;const fy=position==='QB'?4.7:position==='RB'?4.15:6;const ypa=clamp(rate(original,'rush_yd','rush_att',fy)*soften(plan.rushingEfficiencyFactor),position==='WR'?2.5:2.2,position==='WR'?11:8.5);const tdr=clamp(rate(original,'rush_td','rush_att',position==='QB'?.035:.026)*soften(plan.rushingTouchdownFactor),.004,.11);line.rush_att=a;line.rush_yd=a*ypa;line.rush_td=a*tdr;line.rush_fd=a*(position==='QB'?.22:.2);}
   if(['RB','WR','TE'].includes(position)){const n=target?.amount||0;const fc=position==='RB'?.73:position==='TE'?.68:.63;const fy=position==='RB'?6.2:position==='TE'?7:8;const cr=clamp(rate(original,'rec','rec_tgt',fc),.42,.88);const ypt=clamp(rate(original,'rec_yd','rec_tgt',fy)*soften(plan.passingEfficiencyFactor),4,12.5);const tdr=clamp(rate(original,'rec_td','rec_tgt',position==='TE'?.052:.05)*soften(plan.passingTouchdownFactor),.01,.12);line.rec_tgt=n;line.rec=n*cr;line.rec_yd=n*ypt;line.rec_td=n*tdr;line.rec_fd=line.rec*(position==='TE'?.48:position==='RB'?.38:.44);}
   refreshBonuses(line,position);const rawReconciled=Math.max(0,score(line,args.scoring,position));const reconciled=rawReconciled*active;const individual=Math.max(0,c.base.projection);const fantasy=c.fantasyBaseline;const fantasyWeight=(fantasy?.anchorWeight||0)*active;const teamWeight=position==='QB'?.72:.68;const individualWeight=1-teamWeight;const model=(reconciled*teamWeight)+(individual*individualWeight);const fantasyExpected=(fantasy?.weightedPoints||0)*active;const computed=fantasy?model*(1-fantasyWeight)+fantasyExpected*fantasyWeight:model;const projection=Number.isFinite(c.override?.projectionPoints)?Math.max(0,Number(c.override?.projectionPoints)):computed;
   const label=position==='QB'?`${finite(line.pass_att).toFixed(0)} pass attempts, ${finite(line.rush_att).toFixed(1)} rushes`:position==='RB'?`${finite(line.rush_att).toFixed(1)} carries, ${finite(line.rec_tgt).toFixed(1)} targets`:`${finite(line.rec_tgt).toFixed(1)} targets${finite(line.rush_att)>=.5?`, ${finite(line.rush_att).toFixed(1)} rushes`:''}`;
   const context=profile.changedTeams?'Previous-team production remains a meaningful fantasy baseline while current-team opportunity is reconciled separately.':profile.rookie&&profile.sampleGames===0?'NFL workload uses a rookie prior informed by draft capital and current role.':null;const override=c.override?(c.override.note?`Manual projection override: ${c.override.note}`:'A temporary manual projection override is active.'):null;
   players.push({...c.base,projection:Number(projection.toFixed(1)),baseline:Number(computed.toFixed(1)),statLine:Object.fromEntries(Object.entries(line).map(([k,v])=>[k,Number(v.toFixed(3))])),expectedRole:roleLabel(c,targetShare,carryShare,passShare),workload:label,assumption:mergeAssumption(c.base.assumption,context,override),startProbability:start,activeProbability:active,availabilityWeight:active,targetShare:target?Number(targetShare.toFixed(3)):undefined,carryShare:carry?Number(carryShare.toFixed(3)):undefined,teamPassAttempts:Number(plan.passAttempts.toFixed(1)),teamRushAttempts:Number(plan.rushAttempts.toFixed(1)),allocationSource:c.override?.projectionPoints!=null?'manual':plan.source,overrideApplied:Boolean(c.override),workloadUncertainty:Number((plan.uncertaintyMultiplier*(profile.changedTeams?1.06:profile.rookie&&profile.sampleGames===0?1.18:1)).toFixed(3)),projectionTrace:{individualModelPoints:Number(individual.toFixed(2)),reconciledStatLinePoints:Number(reconciled.toFixed(2)),fantasyBaselinePoints:fantasy?Number(fantasy.weightedPoints.toFixed(2)):null,fantasyBaselineWeight:Number(fantasyWeight.toFixed(3)),teamOpportunityWeight:teamWeight,activeProbability:active,adjustments:[profile.changedTeams?'team-change-continuity':'same-team-continuity',fantasy?.established?'established-fantasy-baseline':'limited-or-no-fantasy-baseline',`participation-${participationFactor(c,profile).toFixed(3)}`]}});
  }
 }
 return{players,plans};
}
